### ISSUE TITLE
Request: Publish add-on to Firefox Extension Store

### ISSUE THREAD

**Issue by AnsonH** [Arcaneless/HKUST-Timetable-Planner-Addon#1]
This extension is currently only available in Chrome extension store. However, is it possible for to you publish this extension to the [Firefox Extension Store](https://addons.mozilla.org/en-US/firefox/) too?

I've tried running your code in Firefox and it works perfectly. Therefore, there is no need to modify your codebase and you can directly publish it to the Firefox Extension Store.

Thank you so much for developing this extension 😄 

Here are some useful documentation:
* [Your first Firefox extension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension)
* [Submitting an add-on](https://extensionworkshop.com/documentation/publish/submitting-an-add-on/)

**Comment by Arcaneless** [comment]
Thank you for your suggestion.

I will look into that later.🙏

**Comment by Arcaneless** [comment]
The Firefox add-on is approved.
https://addons.mozilla.org/en-GB/firefox/addon/hkust-timetable-addon/
